# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24e925081abc69448b37a6f2ce111fdace6d352eef04e189f786988e03fb6d194ecb60c32b3339aa5b5b076692b6936c2f3c69f4b3e0538cdc736d5fa3a25beb

test:
  secret_key_base: 4e5c2f32b1eb3091d22ed9ad56957da315e3e911b8ae3b5af10909e82ae1611319242b606b5841aaa729d1a2d0e67ce0cb14f41273f72d9b9154f360cb93b3ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
